"""
Streamlit interface (Section 8: INTERFACE layer).

Two tabs:
  - Student Chat: ask advising questions in plain language
  - Advisor Dashboard: see the prioritized at-risk / borderline student list
"""

import os
import streamlit as st
import pandas as pd

from tools import list_at_risk_students, check_student_progress
from agent import ask

st.set_page_config(page_title="UGBS Advising Assistant", page_icon="🎓", layout="wide")

st.title("🎓 Data Science & Business Analytics — Advising Assistant")
st.caption("OMIS 404 Term Project · Scenario 12: Departmental Academic Advising and Student Progress Support")

if not os.environ.get("GEMINI_API_KEY"):
    st.warning(
        "No GEMINI_API_KEY found in your environment. The Student Chat tab needs "
        "this to work. Set it with:\n\n"
        "Windows (PowerShell): `$env:GEMINI_API_KEY=\"your-key-here\"`\n\n"
        "Then restart Streamlit. The Advisor Dashboard tab works without it, "
        "since it only uses the rule-based tool, not the LLM."
    )

tab1, tab2 = st.tabs(["💬 Student Chat", "📊 Advisor Dashboard"])

# ------------------------------------------------------------------
# TAB 1: Student Chat
# ------------------------------------------------------------------
with tab1:
    st.subheader("Ask an advising question")
    st.caption(
        "Example questions: \"What are the prerequisites for OMIS 301?\", "
        "\"Am I on track to graduate? My student ID is 10910040\", "
        "\"What happens if I fail a core course twice?\""
    )

    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    for turn in st.session_state.chat_history:
        with st.chat_message(turn["role"]):
            st.markdown(turn["text"])

    user_input = st.chat_input("Type your question...")
    if user_input:
        st.session_state.chat_history.append({"role": "user", "text": user_input})
        with st.chat_message("user"):
            st.markdown(user_input)

        with st.chat_message("assistant"):
            if not os.environ.get("GEMINI_API_KEY"):
                answer = "GEMINI_API_KEY is not set, so I can't reach the AI model. Please set it and restart the app."
            else:
                with st.spinner("Thinking..."):
                    try:
                        answer = ask(user_input, history=st.session_state.chat_history[:-1])
                    except Exception as e:
                        answer = f"Something went wrong: {e}"
            st.markdown(answer)

        st.session_state.chat_history.append({"role": "assistant", "text": answer})

# ------------------------------------------------------------------
# TAB 2: Advisor Dashboard
# ------------------------------------------------------------------
with tab2:
    st.subheader("Students needing attention")
    st.caption(
        "Generated by the rule-based progress-check tool, applying the department's "
        "actual progression rules to each student's record. No LLM is used here, "
        "this view is deterministic and explainable by design (see Section 7.2 of the report)."
    )

    students = list_at_risk_students()

    col1, col2 = st.columns(2)
    at_risk_count = sum(1 for s in students if s["status"] == "at_risk")
    borderline_count = sum(1 for s in students if s["status"] == "borderline")
    col1.metric("At-risk students", at_risk_count)
    col2.metric("Borderline students", borderline_count)

    if students:
        df = pd.DataFrame([
            {
                "Student ID": s["student_id"],
                "Name": s["name"],
                "Year": s["year"],
                "Advisor": s["advisor"],
                "Cumulative GPA": s["cumulative_gpa"],
                "Status": s["status"].replace("_", " ").upper(),
            }
            for s in students
        ])
        st.dataframe(df, use_container_width=True, hide_index=True)

        st.divider()
        st.subheader("Look up an individual student")
        selected_id = st.selectbox(
            "Select a student to see the full reasoning:",
            options=[s["student_id"] for s in students],
            format_func=lambda sid: next(s["name"] for s in students if s["student_id"] == sid),
        )
        if selected_id:
            result = check_student_progress(selected_id)
            st.markdown(f"**{result['name']}** ({result['student_id']}) — Year {result['year']} — Advisor: {result['advisor']}")
            st.markdown(f"Cumulative GPA: **{result['cumulative_gpa']:.2f}** — Status: **{result['status'].upper()}**")
            for reason in result["reasons"]:
                st.markdown(f"- {reason}")
    else:
        st.success("No students currently flagged. Everyone is on track.")
